project: Speech enhancement

name: UNet


dir:

  Exp: Exp
  Output: Exp/Temporary
  Output_Best: Exp/Best
  Model_Output: Exp/
  Model_Output_Best: /media/mayank/0b40607e-7efc-4216-b12f-8bb86facfaed/Text/Models_Best

  Plots: Exp/Plots



log_interval_steps: 20

test_now: 60

cummulative_batch_steps: 1

n_channels: 2
n_classes: 2

lr: 0.0001

optimizer: Adam

cuda: True
seed: 2

epoch: 3


batch_size: 1

PreTrained_model:
  check: False
  checkpoint: /media/mayank/0b40607e-7efc-4216-b12f-8bb86facfaed/Text/Models/4500_0_checkpoint.pth.tar
  checkpoint_info: /media/mayank/0b40607e-7efc-4216-b12f-8bb86facfaed/Text/Models/4500_0_info_checkpoint.pth.tar
  checkpoint_best: /media/mayank/0b40607e-7efc-4216-b12f-8bb86facfaed/Text/Models_Best/0_0_checkpoint.pth.tar
  checkpoint_best_info: /media/mayank/0b40607e-7efc-4216-b12f-8bb86facfaed/Text/Models_Best/0_0_info_checkpoint.pth.tar




